version: '3.1'

services:
  postgresql-users:
    image: 'postgres:11'
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DATABASE: postgres
    volumes:
      - './init/init-users-db.sh:/docker-entrypoint-initdb.d/init-users-db.sh'
#      - './init/database.sql:/docker-entrypoint-initdb.d/database.sql'
#      - './init/insert.sql:/docker-entrypoint-initdb.d/insert.sql'
      - './data:/var/lib/postgresql/data'
      - './init:/var/lib/postgresql/init'
    ports:
      - '5433:5432'
    stdin_open: true # docker run -i
    tty: true  # docker run -t
#    command: bash -c "chmod +x /var/lib/postgresql/init/init-users-db.sh && ./var/lib/postgresql/init/init-users-db.sh"

volumes:
  data:
    driver: local