server.port: 8082
spring:
  application.name: iskander4j-backend-devices
  devtools:
    restart:
      enabled: true
eureka:
  client:
    enabled: false
    service-url.defaultZone: 'http://localhost:8010/eureka'