server.port: 8082
spring:
  data:
    mongodb:
      uri: 'mongodb://clever_admin:admin@localhost:27017/cleverhause_devices_db?authMechanism=SCRAM-SHA-1'

logging.level.org.springframework.data: debug